// tarot-cards.js — dados compartilhados entre guia e diário
const TAROT_CARDS = {
  // ── ARCANOS MAIORES ──
  'O Louco':         { num:'0',   oracle:'talvez', keywords:['Começos','Liberdade','Fé cega'],        meaning:'Novo começo, salto de fé, espontaneidade. A ingenuidade sagrada como coragem.' },
  'O Mago':          { num:'I',   oracle:'sim',    keywords:['Manifestação','Vontade','Habilidade'],   meaning:'Poder de manifestar, criatividade ativa. Você tem todas as ferramentas necessárias.' },
  'A Sacerdotisa':   { num:'II',  oracle:'talvez', keywords:['Intuição','Mistério','Sabedoria'],       meaning:'O mundo interior fala. Silêncio, espera e confiança na voz interna.' },
  'A Imperatriz':    { num:'III', oracle:'sim',    keywords:['Fertilidade','Abundância','Natureza'],   meaning:'Criatividade fértil, abundância, maternidade. Nutrir e deixar florescer.' },
  'O Imperador':     { num:'IV',  oracle:'sim',    keywords:['Autoridade','Estrutura','Disciplina'],   meaning:'Liderança, ordem e estabilidade. Construir com firmeza sobre bases sólidas.' },
  'O Hierofante':    { num:'V',   oracle:'talvez', keywords:['Tradição','Espiritualidade','Ensino'],   meaning:'Tradição, mentor espiritual, comprometimento formal. Respeitar o processo.' },
  'Os Amantes':      { num:'VI',  oracle:'sim',    keywords:['Escolha','Amor','Valores'],              meaning:'Decisão consciente, alinhamento de valores, união dos opostos.' },
  'O Carro':         { num:'VII', oracle:'sim',    keywords:['Vitória','Controle','Movimento'],        meaning:'Triunfo pela força de vontade. Manter o foco enquanto o mundo gira.' },
  'A Força':         { num:'VIII',oracle:'sim',    keywords:['Coragem','Compaixão','Força interior'],  meaning:'Domesticar os instintos com amor, não repressão. Coragem que vem do coração.' },
  'O Eremita':       { num:'IX',  oracle:'talvez', keywords:['Solidão','Sabedoria','Introspecção'],    meaning:'Recolhimento necessário, busca interior. A lanterna ilumina só o próximo passo.' },
  'Roda da Fortuna': { num:'X',   oracle:'sim',    keywords:['Ciclos','Destino','Karma'],              meaning:'A roda gira sempre. Reconheça em que ponto está e flua com o movimento.' },
  'A Justiça':       { num:'XI',  oracle:'talvez', keywords:['Equilíbrio','Verdade','Causa e efeito'], meaning:'Verdade objetiva, causa e efeito, honestidade radical consigo mesma.' },
  'O Enforcado':     { num:'XII', oracle:'nao',    keywords:['Sacrifício','Pausa','Nova perspectiva'], meaning:'Entrega voluntária, ver de outro ângulo. Parar de lutar para enxergar mais.' },
  'A Morte':         { num:'XIII',oracle:'talvez', keywords:['Transformação','Fim de ciclo','Renovação'], meaning:'Metamorfose radical. O que deve morrer para que você viva mais plenamente?' },
  'A Temperança':    { num:'XIV', oracle:'talvez', keywords:['Equilíbrio','Alquimia','Moderação'],     meaning:'Mistura gradual, paciência como virtude. A cura que não pode ser apressada.' },
  'O Diabo':         { num:'XV',  oracle:'nao',    keywords:['Sombra','Vício','Apego'],                meaning:'As correntes que criamos nós mesmos. O que você se recusa a soltar?' },
  'A Torre':         { num:'XVI', oracle:'nao',    keywords:['Ruptura','Revelação','Libertação'],      meaning:'Destrói só o que estava podre. Dolorosa mas necessária libertação.' },
  'A Estrela':       { num:'XVII',oracle:'sim',    keywords:['Esperança','Cura','Renovação'],          meaning:'Após toda destruição, a beleza retorna. Fase de graça e conexão com o divino.' },
  'A Lua':           { num:'XVIII',oracle:'nao',   keywords:['Ilusão','Inconsciente','Medo'],          meaning:'As coisas não são como parecem. Enfrente os medos antes de agir.' },
  'O Sol':           { num:'XIX', oracle:'sim',    keywords:['Alegria','Sucesso','Vitalidade'],         meaning:'Clareza plena, celebração, sucesso. A consciência que ilumina tudo.' },
  'O Julgamento':    { num:'XX',  oracle:'sim',    keywords:['Renascimento','Chamado','Despertar'],     meaning:'Chamado ao propósito. Está vivendo de acordo com o que sua alma veio fazer?' },
  'O Mundo':         { num:'XXI', oracle:'sim',    keywords:['Completude','Realização','Integração'],  meaning:'Ciclo completo com honra. Tornar-se quem verdadeiramente se é.' },

  // ── COPAS ──
  'Ás de Copas':        { naipe:'Copas', oracle:'sim',    keywords:['Novo amor','Abertura emocional'],   meaning:'Coração aberto e abundante. Novo começo emocional, amor que surge.' },
  'Dois de Copas':      { naipe:'Copas', oracle:'sim',    keywords:['União','Parceria','Reciprocidade'],  meaning:'Dar e receber em igual medida. O amor mais equilibrado do baralho.' },
  'Três de Copas':      { naipe:'Copas', oracle:'sim',    keywords:['Celebração','Amizade','Comunidade'], meaning:'Alegria compartilhada, encontros felizes, conquistas celebradas juntas.' },
  'Quatro de Copas':    { naipe:'Copas', oracle:'nao',    keywords:['Contemplação','Tédio','Indiferença'],meaning:'A bênção está sendo ignorada. Aprecie o que já existe antes de pedir mais.' },
  'Cinco de Copas':     { naipe:'Copas', oracle:'nao',    keywords:['Perda','Luto','Tristeza'],           meaning:'Virar-se para o que restou em vez de só lamentar o que se perdeu.' },
  'Seis de Copas':      { naipe:'Copas', oracle:'talvez', keywords:['Nostalgia','Infância','Passado'],    meaning:'Memórias doces, reencontros, inocência. Cuidado com idealização do passado.' },
  'Sete de Copas':      { naipe:'Copas', oracle:'nao',    keywords:['Ilusões','Muitas escolhas','Fantasia'],meaning:'Excesso de possibilidades paralisa. Discernimento entre o real e o fantasioso.' },
  'Oito de Copas':      { naipe:'Copas', oracle:'nao',    keywords:['Partida','Busca espiritual','Deixar ir'],meaning:'Abandono voluntário em busca de algo mais profundo. Coragem de deixar para trás.' },
  'Nove de Copas':      { naipe:'Copas', oracle:'sim',    keywords:['Satisfação','Desejo realizado','Prazer'],meaning:'A carta dos desejos. Realização emocional genuína, contentamento pleno.' },
  'Dez de Copas':       { naipe:'Copas', oracle:'sim',    keywords:['Família','Harmonia','Felicidade'],    meaning:'O lar ideal, amor familiar completo, paz duradoura. Realização emocional máxima.' },
  'Valete de Copas':    { naipe:'Copas', oracle:'talvez', keywords:['Mensagem emocional','Jovem sensitivo'],meaning:'Mensagens do mundo espiritual, intuição em desenvolvimento, sonhos.' },
  'Cavaleiro de Copas': { naipe:'Copas', oracle:'sim',    keywords:['Romance','Proposta','Mensageiro'],    meaning:'Propostas românticas, convites, mensagens de amor. Energia suave e poética.' },
  'Rainha de Copas':    { naipe:'Copas', oracle:'sim',    keywords:['Empatia','Intuição madura','Cuidado'], meaning:'Cuidado profundo, psíquico desenvolvido, amor maduro e curador.' },
  'Rei de Copas':       { naipe:'Copas', oracle:'sim',    keywords:['Sabedoria emocional','Equilíbrio'],    meaning:'Sentir tudo sem ser arrastado. Líder que usa o coração como bússola.' },

  // ── ESPADAS ──
  'Ás de Espadas':        { naipe:'Espadas', oracle:'sim',    keywords:['Clareza','Verdade','Breakthrough'],   meaning:'A espada da verdade corta toda ilusão. Clareza mental repentina, decisão firme.' },
  'Dois de Espadas':      { naipe:'Espadas', oracle:'nao',    keywords:['Impasse','Decisão difícil','Evitação'],meaning:'Recusa de ver a realidade. Decisão adiada que precisa ser tomada.' },
  'Três de Espadas':      { naipe:'Espadas', oracle:'nao',    keywords:['Dor','Traição','Separação'],          meaning:'A dor que não pode ser evitada. Separação, traição, desgosto — mas passa.' },
  'Quatro de Espadas':    { naipe:'Espadas', oracle:'talvez', keywords:['Descanso','Recuperação','Pausa'],      meaning:'Após batalhas mentais, descansar. O guerreiro que não repousa perde a próxima.' },
  'Cinco de Espadas':     { naipe:'Espadas', oracle:'nao',    keywords:['Conflito','Derrota','Vitória vazia'],  meaning:'Vencer a qualquer custo tem consequências. Conflitos sem vencedores reais.' },
  'Seis de Espadas':      { naipe:'Espadas', oracle:'talvez', keywords:['Transição','Afastamento','Calmaria'],  meaning:'Transição difícil mas necessária para águas mais calmas.' },
  'Sete de Espadas':      { naipe:'Espadas', oracle:'nao',    keywords:['Estratégia','Desonestidade','Furtividade'],meaning:'Cuidado com quem ou o que não é o que parece. Traição ou estratégia necessária.' },
  'Oito de Espadas':      { naipe:'Espadas', oracle:'nao',    keywords:['Aprisionamento mental','Limitação'],   meaning:'A prisão é mental. Crenças limitantes, ansiedade — a venda pode ser tirada.' },
  'Nove de Espadas':      { naipe:'Espadas', oracle:'nao',    keywords:['Ansiedade','Pesadelo','Angústia'],     meaning:'Pensamentos catastróficos às 3 da manhã. A situação é menos grave do que parece.' },
  'Dez de Espadas':       { naipe:'Espadas', oracle:'nao',    keywords:['Fim doloroso','Toque do fundo'],       meaning:'O pior já passou. Fim inevitável, mas o amanhecer começa no horizonte.' },
  'Valete de Espadas':    { naipe:'Espadas', oracle:'talvez', keywords:['Curiosidade','Vigilância','Notícias'], meaning:'Notícias chegando, pensamento crítico, perspicácia aguçada.' },
  'Cavaleiro de Espadas': { naipe:'Espadas', oracle:'sim',    keywords:['Velocidade','Ação direta','Impulsividade'],meaning:'Decisões rápidas, comunicação direta. Energia que resolve mas pode atropelar.' },
  'Rainha de Espadas':    { naipe:'Espadas', oracle:'talvez', keywords:['Clareza','Independência','Percepção'], meaning:'Mulher que passou por dor e tornou-se sábia. Pede a verdade antes da gentileza.' },
  'Rei de Espadas':       { naipe:'Espadas', oracle:'sim',    keywords:['Autoridade intelectual','Razão'],       meaning:'Julgamento claro, mente superior. Autoridade que usa a lógica com justiça.' },

  // ── OUROS ──
  'Ás de Ouros':        { naipe:'Ouros', oracle:'sim',    keywords:['Prosperidade','Nova oportunidade'],   meaning:'Semente de abundância. Nova oportunidade financeira ou material surgindo.' },
  'Dois de Ouros':      { naipe:'Ouros', oracle:'talvez', keywords:['Malabarismo','Equilíbrio','Flexibilidade'],meaning:'Múltiplas responsabilidades em equilíbrio. Adaptação com humor e destreza.' },
  'Três de Ouros':      { naipe:'Ouros', oracle:'sim',    keywords:['Trabalho em equipe','Habilidade','Reconhecimento'],meaning:'Colaboração, aprendizado de um ofício, trabalho reconhecido.' },
  'Quatro de Ouros':    { naipe:'Ouros', oracle:'nao',    keywords:['Controle','Apego','Possessividade'],   meaning:'Apego ao dinheiro, medo de perder o que se tem. O que você se recusa a soltar?' },
  'Cinco de Ouros':     { naipe:'Ouros', oracle:'nao',    keywords:['Dificuldade financeira','Exclusão'],    meaning:'Dificuldades materiais. A luz (ajuda) está mais perto do que parece — peça.' },
  'Seis de Ouros':      { naipe:'Ouros', oracle:'sim',    keywords:['Generosidade','Dar e receber','Equilíbrio'],meaning:'Equilíbrio entre dar e receber. Caridade genuína, pagamentos chegando.' },
  'Sete de Ouros':      { naipe:'Ouros', oracle:'talvez', keywords:['Paciência','Investimento','Avaliação'], meaning:'O trabalho foi feito — aguarde os frutos. Vale o esforço o retorno?' },
  'Oito de Ouros':      { naipe:'Ouros', oracle:'sim',    keywords:['Dedicação','Aperfeiçoamento','Aprendizado'],meaning:'Maestria que vem com a prática. Dedicação ao trabalho, melhoria contínua.' },
  'Nove de Ouros':      { naipe:'Ouros', oracle:'sim',    keywords:['Abundância','Autossuficiência','Prazer'], meaning:'Independência financeira conquistada. Prosperidade e luxo merecidos.' },
  'Dez de Ouros':       { naipe:'Ouros', oracle:'sim',    keywords:['Herança','Legado','Segurança familiar'],  meaning:'Riqueza que se perpetua. Herança, investimentos de longo prazo, segurança.' },
  'Valete de Ouros':    { naipe:'Ouros', oracle:'talvez', keywords:['Estudante','Novo projeto','Prático'],     meaning:'Aprendizado prático, novo projeto em estágio inicial. Jovem confiável.' },
  'Cavaleiro de Ouros': { naipe:'Ouros', oracle:'talvez', keywords:['Responsabilidade','Diligência','Confiabilidade'],meaning:'O mais lento dos cavaleiros, mas o mais confiável. Resultados sólidos.' },
  'Rainha de Ouros':    { naipe:'Ouros', oracle:'sim',    keywords:['Prosperidade','Nutrição prática','Conforto'],meaning:'O lar como templo, cuidado com o corpo e o dinheiro. Abundância prática.' },
  'Rei de Ouros':       { naipe:'Ouros', oracle:'sim',    keywords:['Riqueza','Liderança','Sucesso consolidado'],meaning:'Sucesso financeiro com sabedoria. O empreendedor generoso e bem-sucedido.' },

  // ── PAUS ──
  'Ás de Paus':        { naipe:'Paus', oracle:'sim',    keywords:['Inspiração','Potencial criativo','Ação'],  meaning:'Faísca de inspiração, início cheio de entusiasmo, energia vital em seu ápice.' },
  'Dois de Paus':      { naipe:'Paus', oracle:'talvez', keywords:['Planejamento','Visão de futuro','Decisão'],meaning:'Visão clara, mas o passo ainda não foi dado. Hora de planejar com estratégia.' },
  'Três de Paus':      { naipe:'Paus', oracle:'sim',    keywords:['Expansão','Viagem','Resultados chegando'], meaning:'O que foi semeado começa a retornar. Expansão de projetos e horizontes.' },
  'Quatro de Paus':    { naipe:'Paus', oracle:'sim',    keywords:['Celebração','Lar feliz','Comunidade'],     meaning:'Casamento, celebrações, harmonia no lar. Pausa para comemorar conquistas.' },
  'Cinco de Paus':     { naipe:'Paus', oracle:'nao',    keywords:['Conflito','Competição','Caos'],            meaning:'Energia dispersa em várias direções. Competição que pode desgastar.' },
  'Seis de Paus':      { naipe:'Paus', oracle:'sim',    keywords:['Vitória','Reconhecimento público','Sucesso'],meaning:'Triunfo reconhecido. Colher os louros com humildade após longa luta.' },
  'Sete de Paus':      { naipe:'Paus', oracle:'talvez', keywords:['Defesa','Perseverança','Posição'],          meaning:'Manter-se firme contra adversidades. Você tem terreno elevado — defenda-o.' },
  'Oito de Paus':      { naipe:'Paus', oracle:'sim',    keywords:['Movimento veloz','Comunicação','Mensagens'],meaning:'Tudo acontecendo de uma vez e rápido. Notícias chegando, viagem iminente.' },
  'Nove de Paus':      { naipe:'Paus', oracle:'talvez', keywords:['Resistência','Exaustão','Determinação'],    meaning:'Cansaço profundo mas ainda de pé. Reúna as últimas forças para cruzar a linha.' },
  'Dez de Paus':       { naipe:'Paus', oracle:'nao',    keywords:['Sobrecarga','Fardo excessivo','Responsabilidade'],meaning:'Você carrega mais do que deve. Hora de delegar ou largar o que não é seu.' },
  'Valete de Paus':    { naipe:'Paus', oracle:'sim',    keywords:['Entusiasmo','Aventura','Energia criativa'],  meaning:'Boas notícias, energia adventurosa. A faísca que precisa ser canalizada.' },
  'Cavaleiro de Paus': { naipe:'Paus', oracle:'sim',    keywords:['Aventura','Paixão','Ação impulsiva'],        meaning:'Energia irresistível, sedutor, apaixonado. Mudanças de rumo frequentes.' },
  'Rainha de Paus':    { naipe:'Paus', oracle:'sim',    keywords:['Confiança','Carisma','Liderança natural'],   meaning:'Solar, exuberante, confiante. Criatividade e paixão de vida irresistíveis.' },
  'Rei de Paus':       { naipe:'Paus', oracle:'sim',    keywords:['Visão','Empreendedorismo','Liderança'],      meaning:'Líder visionário, empreendedor nato. Inspira pelo fogo da visão.' },
};
